### PR TITLE
improved on the GUI a bit, added download functionality

### PR DESCRIPTION
**Pull request by sbordeyne**

### CODE REVIEW

**Comment by cyian-1756** [comment]
Trying to run this throws an error

```
 File "GUI/gui.py", line 100
    url = g[f"download_link_{current_os}"]
                                        ^
```

Also isn't pulling in wget a bit much? There's already a func to download games in pyfuncs (That also handles errors like links that can't be downloaded from easily (like mega)).

**Comment by sbordeyne** [comment]
The error is likely due to the syntax which is only for python 3.6.5+

**Comment by sbordeyne** [comment]
it should be all good now, though, the threading might require some more work to actually show the progress, and not hang the program while it is downloading.

**Comment by cyian-1756** [comment]
Looks pretty good, but it silently fails if the game doesn't support the users OS. The following error is printed on the command line

```
requests.exceptions.MissingSchema: Invalid URL "Doesn't support": No schema supplied. Perhaps you meant http://Doesn't support?
```

The gui should tell the user the game doesn't support their OS and give them an option to download the game for a different OS

**Comment by cyian-1756** [comment]
~~The gui window also doesn't close when it gets a KeyboardInterrupt~~ It seems to work after your last push

**Comment by cyian-1756** [comment]
Trying to download a game seems to freeze the gui ( I can't click anything, the entire window is black, Clicking the x to close the window doesn't do anything)

**Comment by cyian-1756** [comment]
Trying to add a new game using the GUI errors out with

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/tmp/nsfw_game_updater/GUI/add_new.py", line 150, in onOkButton
    "animation":self.has_animation,\
AttributeError: 'AddNewGUI' object has no attribute 'has_animation'
```

**Comment by sbordeyne** [comment]
The UI hanging when downloading is because for some reason the download doesn't start in another thread, as it should.

**Comment by sbordeyne** [comment]
the issues you mentionned are fixed (hopefully). You can now merge the branches, and I'll see what other features I may implement

**Comment by cyian-1756** [comment]
I found one issue in your latest push, adding a game from the gui doesn't add the graphtreon to the json which means what when you try to restart the gui it errors out with

```
Traceback (most recent call last):
  File "GUI/gui.py", line 195, in <module>
    gui = GUI(root)
  File "GUI/gui.py", line 34, in __init__
    self.init_layout()
  File "GUI/gui.py", line 47, in init_layout
    self.init_treeview()
  File "GUI/gui.py", line 81, in init_treeview
    self.add_games_to_tree()
  File "GUI/gui.py", line 89, in add_games_to_tree
    info["visual_style"], info["animation"], info["public_build"], info["graphtreon"])
KeyError: 'graphtreon'
```

Fix that and I'll merge it. On a side note thanks for contributing, having a GUI makes this project a lot more usable

**Comment by sbordeyne** [comment]
probably a typo, i'll check it out

**Comment by sbordeyne** [comment]
fixed

**Comment by cyian-1756** [comment]
Now the gui errors out with 

```
Traceback (most recent call last):
  File "gui.py", line 16, in <module>
    from constants import *
  File "/tmp/nsfw_game_updater/GUI/constants.py", line 9, in <module>
    config.read("config.cfg")
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1012, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 109: invalid start byte
```

**Comment by cyian-1756** [comment]
It seems it errored out because you had the char "" in GUI/config.cfg at line 8 in the word "Doesnt". Replace "" with a "'" and it works

So make that one change and I'll merge

**Comment by sbordeyne** [comment]
that's an issue with your json, not my code though. The code adds the version downloaded (from the json) to keep track to the config.cfg file. The bugged unicode character must be in the json file.

**Comment by cyian-1756** [comment]
> The bugged unicode character must be in the json file

In that case I'll merge this

**Comment by sbordeyne** [comment]
fixed, though I need to add some kind of character checking to the add_new_game entry boxes. If an user tries to enter an improper character, this bug will appear again.

**Pull request merged**
